### ISSUE TITLE
[Template] Add sidebar links to news landing and detail pages

### ISSUE THREAD

**Issue by dave-fink** [aemsites/hubblehomes-com#110]
Add sidebar to News landing and news detail pages.

https://www.hubblehomes.com/news

https://www.hubblehomes.com/news/news-detail/building-a-greener-future-hubble-homes-receives-2024-energy-star-market-leader-award-161

![image](https://github.com/aemsites/hubblehomes-com/assets/138233107/8d44caa7-4c4c-42e6-904b-7c3d1b134c21)

**Comment by samuelopra** [comment]
@varunmitra @bhellema was this still needed?

**Comment by bhellema** [comment]
The side bar was reduced in content and recent news was added to the bottom of the article page.  I don't think there's anything left to do for this ticket.

**Comment by codevoyage** [comment]
Based on confirmation from the customer, this issue is no longer relevant.
