### ISSUE TITLE
[Importer] - Communities pages require fragment to disclaimer

### ISSUE THREAD

**Issue by bhellema** [aemsites/hubblehomes-com#111]
A fragment block needs to be added to the communities page that points to the disclaimer.  

![image](https://github.com/aemsites/hubblehomes-com/assets/6395150/94b86533-0512-47be-b8be-f89a8fbb8485)

**Comment by codevoyage** [comment]
Does this need the (disclaimer) in the table heading? eg:
`Fragment(disclaimer)`
