### ISSUE TITLE
[Embed Block] Add support for CloudFront (AWS) video source

### ISSUE THREAD

**Issue by codevoyage** [aemsites/hubblehomes-com#138]
Some Hubble Home pages have videos served from AWS CloudFront, which the Embed block does not currently support. Support for AWS embeds needs to be added to the Embed block.

Example of a page containing a CloudFront video: https://www.hubblehomes.com/news/news-detail/were-still-here-for-you-during-covid-19-13

**Comment by bhellema** [comment]
Added an animoto embed, in place of the aws.
