### ISSUE TITLE
Search results - undefined

### ISSUE THREAD

**Issue by kunwarsaluja** [aemsites/hubblehomes-com#171]
**Steps to reproduce**
- Navigate to homepage
- Use the search bar and search for 'ridge'
- Click on results like 'Canyons at Prescott Ridge - Community'
- See it navigate to 'https://main--hubblehomes-com--aemsites.hlx.page/undefined'

Not sure if this is content problem or a bug in code so might need some investigation.

![Screenshot 2024-07-15 at 11 56 19 AM](https://github.com/user-attachments/assets/dbcd9847-46ad-4121-8f21-cddb8b1243c7)

**Comment by varunmitra** [comment]
This is a data issue, since the actual data is missing for some of these pages as such it returns an undefined. Issue should be resolved once we have all the data imported in.
