### ISSUE TITLE
[Search] Index all pages from current hubblehomes

### ISSUE THREAD

**Issue by samuelopra** [aemsites/hubblehomes-com#181]
This task is created for all the work left for importing pages that are not currently indexed.

- Pages from the data room are currently being indexed
- Pages that need to be indexed from the query-index are currently not being indexed
- Many Individual pages that are not yet implemented still need to be indexed ( i.e. Financial page, inspiration page )

**Comment by bhellema** [comment]
@samuelopra @varunmitra do you guys see us needing this task still?
