### ISSUE TITLE
Subscribe to newsletter form

### ISSUE THREAD

**Issue by codevoyage** [aemsites/hubblehomes-com#245]
Create a Subscription Page for the Hubble Homes Newsletter

	•	Add a link to this page in the footer.
	•	For desktop view, also add the link to the sidebar on the news listing page (as marked on the screenshot).

![Screenshot 2024-08-01 at 1 23 45 PM](https://github.com/user-attachments/assets/5179c02e-6176-4812-9c50-18c1b341eaa9)

**Comment by samuelopra** [comment]
Hey @codevoyage , could you please elaborate on this task? Where can I find this on the `news sidebar on desktop view`
