### ISSUE TITLE
[Bug] Remove Arrow from the Carousel CTA

### ISSUE THREAD

**Issue by varunmitra** [aemsites/hubblehomes-com#251]
![Screen Shot 2024-07-26 at 15 51 09 PM](https://github.com/user-attachments/assets/c17c5bc7-69b7-4e7f-bb6f-0bd072c4b7dd)
Original CTA Button looks like 
![Screen Shot 2024-07-26 at 15 51 24 PM](https://github.com/user-attachments/assets/498a711e-5b93-4cc8-b4af-5bdb9f487dc4)

**Comment by bhellema** [comment]
Fixed in https://github.com/aemsites/hubblehomes-com/commit/ce147b996aabb5e3367a8d42c620021e47e0e893
