### ISSUE TITLE
[Hubspot form] Show a placeholder until the form loads 

### ISSUE THREAD

**Issue by codevoyage** [aemsites/hubblehomes-com#281]
The HubSpot form takes a couple of seconds to load. During this time, nothing on the screen indicates to the end user that the form is loading. 

Show a placeholder image until the form loads.

**Comment by bhellema** [comment]
I don't know if we want a place holder image or some CSS that shows loading.  Something like this https://harshilmoradia.medium.com/how-to-create-css-animated-loading-card-skeleton-ab0827795ae8
