### ISSUE TITLE
Turf Interactive Floorplan Button

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#289]
Seems to be on all floor plan pages. Example: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek/amethyst/19138-beechcraft-st/999
These assets will be going away when the previous development agency is offboarded.

Recommend removing both the grey buttons as the Floor Plan Handout is already available as a link amongst the other links.

**Comment by varunmitra** [comment]
@codevoyage please give this a look. we can update the links block to hide driving instructions. Or we can do this via import script.

**Comment by codevoyage** [comment]
@varunmitrasure, the import can handle removing both buttons.

**Comment by codevoyage** [comment]
@natemyersSHL 

There is a link to the interactive floor plan in the links section on the right, which also needs to be removed along with the button, correct? 
In my next import, I will remove both buttons as shown below, as well as the link to the interactive floor plan on the right from all the pages where this occurs, not just on Floor Plans but also from Inventory models, etc.

![Screenshot 2024-08-09 at 9 13 19 AM](https://github.com/user-attachments/assets/bc2c775f-e28c-48ec-94b1-b47f463e491a)
![Screenshot 2024-08-09 at 9 13 55 AM](https://github.com/user-attachments/assets/f529d38b-0f3b-4bc2-bbbb-7ae81a7e3392)

**Comment by natemyersSHL** [comment]
@codevoyage that's correct. All interactive media will be going away as it's created and hosted by the previous development agency.

**Comment by codevoyage** [comment]
I assume this also includes the interactive sitemap, like this: [Interactive Site Plan](https://www.hubblehomes.com/new-homes/idaho/boise-metro/caldwell/brittany-heights-at-windsor-creek/interactive-site-plan), not just interactive floorplans.
