### ISSUE TITLE
Cannot exit Gallery after opening it up

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#290]
https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999

**Comment by natemyersSHL** [comment]
If you go there from a panel on a community page, a blue bar with an "X" appears above the top. But if you click the "Gallery" button on a floor plan's page that blue bar is missing.

**Comment by varunmitra** [comment]
@samuelopra please give this a look.

**Comment by samuelopra** [comment]
This is fixed, opened https://github.com/aemsites/hubblehomes-com/issues/306 for double scroll bar
