### ISSUE TITLE
Double Scroll bar in gallery

### ISSUE THREAD

**Issue by samuelopra** [aemsites/hubblehomes-com#306]
- Havent reproduced @bhellema please link the page and screen size below

**Comment by bhellema** [comment]
![image](https://github.com/user-attachments/assets/d3a47c37-e362-4f74-b80e-b4f076e7ced8)

https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/caldwell/mason-creek/ridenbaugh/10881-sky-dive-st/999
