### ISSUE TITLE
Generate Builder Digital Experience - BDX Output (XML Generation)

### ISSUE THREAD

**Issue by bhellema** [aemsites/hubblehomes-com#31]
The current system can generate an XML file that can be used as input for 3rd party websites to list the homes from hubblehomes.com

There is an XML specification that can be referenced

<img width="591" alt="image" src="https://github.com/aemsites/hubblehomes-com/assets/6395150/4539fea8-6cce-4e88-b06e-9b3108afb3ea">

**Comment by varunmitra** [comment]
Syndication xml feed to be generated.
Utilize github workflow to generate the feed
