### ISSUE TITLE
Strange Blog Category

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#322]
https://main--hubblehomes-com--aemsites.hlx.page/news/category/

No category name but "(5)" articles are there?

**Comment by bhellema** [comment]
There are 5 articles that exist in the list on page 18.  Not sure if these are articles that are bad imports or what at this point. 

cc: @codevoyage 

![image](https://github.com/user-attachments/assets/02f340f0-4ce5-4589-a71c-e4f12e40d442)

**Comment by bhellema** [comment]
I have cleaned up the pages that were causing this issue and the index has been updated.
