### ISSUE TITLE
AWS Embeds should be renamed animoto

### ISSUE THREAD

**Issue by bhellema** [aemsites/hubblehomes-com#333]
The article https://woodsidegroup.sharepoint.com/:w:/r/sites/HubbleHomesWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B7476B18C-6F57-4D3E-A5C9-BD93E3E8EB34%7D&file=were-still-here-for-you-during-covid-19-13.docx&action=default&mobileredirect=true for example has a embed that is wired up to animoto.  We need to update the import script to change this from AWS to animoto.

**Comment by codevoyage** [comment]
Does the Animoto variant already have the code in the embed block, or does that still need to be implemented?

**Comment by bhellema** [comment]
@codevoyage  It has been implemented a few weeks back.   It's ready!
