### ISSUE TITLE
"Driving Directions" in Links section

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#341]
Driving Directions links to: https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/kuna/sera-sole/driving-directions
We don't have driving directions pages anymore correct? If that's true we can remove these links from all plan/MIRC pages and they can use the button that opens Google Maps.
https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/kuna/sera-sole

**Comment by varunmitra** [comment]
@natemyersSHL with the new import this issue is fixed. Can you please check?

**Comment by natemyersSHL** [comment]
@varunmitra Just checked, this is resolved. Thank you!
