### ISSUE TITLE
"New Home Specialists" section is blank

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#342]
Can we add logic to remove this section/header if no Home Specialists are associated with the plan?
https://main--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/kuna/sera-sole

**Comment by bhellema** [comment]
@varunmitra I have this already fixed in my latest PR.

**Comment by bhellema** [comment]
Resolved
