### ISSUE TITLE
Selecting "Ready Now" as a Map filter returns no results

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#343]
Is this because we just don't have any right now? Or is it a bug?
https://main--hubblehomes-com--aemsites.hlx.page/available/quick-move-ins

**Comment by bhellema** [comment]
I currently see one 
![image](https://github.com/user-attachments/assets/7cfa1736-65fb-4f99-a1ec-7dbc39034d7f)

According to the spread sheet there is only one home which got scraped from the site, so I guess there is only one?!

**Comment by bhellema** [comment]
Code is working as designed.
