### ISSUE TITLE
Directions CTA on "Featured Plans" cards 

### ISSUE THREAD

**Issue by natemyersSHL** [aemsites/hubblehomes-com#344]
Should inherit from the community when clicked from a community page.
Not sure where they are taking me now.
https://main--hubblehomes-com--aemsites.hlx.live/new-homes/idaho/boise-metro/caldwell/mason-creek

**Comment by bhellema** [comment]
@natemyersSHL looks like the logic is pulling up the sales office location for mason creek which maps to Adam's Ridge sales .  For featured cards we just need to pull up the community location not the sales center.
