### ISSUE TITLE
[Bug] Domain changes when clicking on 'Return to Promotions'

### ISSUE THREAD

**Issue by codevoyage** [aemsites/hubblehomes-com#380]
The domain changes when clicking ‘Return to Promotions’ on any of the promotion pages, e.g., from https://www.hubblehomes.com/promotions/promotions-detail/hubble-homes-for-heroes to https://main--hubblehomes-com--aemsites.hlx.page/promotions.

**Comment by bhellema** [comment]
https://github.com/aemsites/hubblehomes-com/pull/379 merged
