### ISSUE TITLE
[Template] Our Locations

### ISSUE THREAD

**Issue by bhellema** [aemsites/hubblehomes-com#64]
The locations page requires a template to render the page. The template should consume the authored items, but the rest of the page can be generated by the template.  The template can leverage the template block "locations"  
 see https://github.com/aemsites/hubblehomes-com/issues/65, to render the different data that can be found in the office and sales agent spread sheet.  

The author should be able to provide a hero image, text and link to a pdf document that will be added to the hero layout. 
![image](https://github.com/aemsites/hubblehomes-com/assets/6395150/7698ebf3-7346-4883-805c-9bf7324d9de5)

The author should be able to provide a list of links that will be rendered as buttons above the locations template block.  
![image](https://github.com/aemsites/hubblehomes-com/assets/6395150/0a0b8f93-30a3-406c-9e63-7d2a355cfea0)

https://www.hubblehomes.com/new-homes/our-locations

**Comment by samuelopra** [comment]
@bhellema does this need to be closed since #65 is closed?

**Comment by bhellema** [comment]
As per the discussion with Nate, the locations page is going to be deleted. https://adobe-dx-support.slack.com/archives/C06P5NMBH6W/p1719346485231029
