### ISSUE TITLE
[block] search block

### ISSUE THREAD

**Issue by varunmitra** [aemsites/hubblehomes-com#8]
![Screenshot 2024-05-02 at 10 53 29 AM](https://github.com/aemsites/hubblehomes-com/assets/12259186/d929153c-c6b4-46be-a717-0c9dd4863b21)

![Screenshot 2024-05-02 at 10 53 43 AM](https://github.com/aemsites/hubblehomes-com/assets/12259186/4c987ae9-2dea-4f44-889f-f885b534fd29)

**Comment by varunmitra** [comment]
- [ ] MLS integration
- [ ] Integration with Map api

**Comment by bhellema** [comment]
Cross duplicate of 11 and 59 issues.  Closing as we have coverage with those two issues.
